apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  labels:
    app: weather-app-project
spec:
  selector:
    app: weather-app-project
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30180
